/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PortfolioSection: typeof import('./src/components/PortfolioSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./src/components/ServicesSection.vue')['default']
  }
}
